version: "3.9"

services:
  api:
    container_name: api
    build: .
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=8080
      - DB_HOST=dockerdev
    volumes:
      - .:/app

  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    env_file:
      - .env
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
